---
- name: Verify the package is installed
  ansible.builtin.command: rpm -q "{{ pkg }}" # noqa command-instead-of-module
  register: pkg_installed
  ignore_errors: true
  changed_when: "pkg_installed.rc != 0"

- name: Install the package
  ansible.builtin.command: yum install -y "{{ pkg }}" # noqa command-instead-of-module no-changed-when
  when: "pkg_installed.rc != 0"
