- name: verify if '{{ pkg }}' package is installed
  command: rpm -q '{{ pkg }}'
  register: pkg_installed
  ignore_errors: True
  changed_when: 'pkg_installed.rc != 0'

- name: install '{{ pkg }}'
  command: yum install -y '{{ pkg }}'
  when: 'pkg_installed.rc != 0'
